Repository tryber/sd-01-week19-recipes-app-1, pull requests merged in 2020-02, with the labels that each got.

#2 Fix sentences
  README.md
Labels: enhancement

#3 Make minimal test coverage a requisite
  README.md
Labels: enhancement

#4 API's
  package-lock.json
  src/services/drinkAPI.js
  src/services/foodAPI.js
Labels: Code Review

#6 adicionando tela de Login
  src/components/LoginButton.jsx
  src/components/LoginForms.jsx
  src/components/LoginPage.jsx
  src/context/Provider.jsx
  src/context/context.jsx
  src/index.js
  src/styles/LoginPage.css
Labels: Code Review

#5 Footer | Recipes App
  src/App.css
  src/App.js
  src/components/Footer.css
  src/components/Footer.jsx
  src/img/drinkIcon.svg
  src/img/explorerIcon.svg
  src/img/foodIcon.svg
Labels: Code Review

#11 Footer Changes | App Receitas
  src/components/Footer.jsx
Labels: Code Review

#8 Header Input | Receitas App
  package-lock.json
  package.json
  src/App.js
  src/components/Input.jsx
  src/context/Provider.jsx
  src/styles/inputSearch.css
Labels: In Progress

#9 Criando página principal de receitas
  src/App.js
  src/components/Categories.css
  src/components/Categories.jsx
  src/components/Food.css
  src/components/Food.jsx
  src/components/FoodList.jsx
  src/components/FoodPage.jsx
  src/components/Footer.jsx
  src/components/LoginButton.jsx
  src/components/LoginForms.jsx
  src/context/Provider.jsx
  src/services/drinkAPI.js
  src/services/foodAPI.js
  src/services/randomLetter.js
  src/styles/Footer.css
Labels: Code Review

#7 Finalizando o componente header
  src/components/Header.jsx
  src/components/Home.jsx
  src/components/Input.jsx
  src/components/Profile.jsx
  src/context/Provider.jsx
  src/img/iconProfile.png
  src/img/iconSearch.png
  src/styles/Header.css
Labels: Code Review

#12 Juntando os componentes e resolvendo os bugs
  package-lock.json
  src/App.js
  src/components/Categories.jsx
  src/components/Food.jsx
  src/components/FoodList.jsx
  src/components/FoodPage.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home.jsx
  src/components/Input.jsx
  src/components/LoginButton.jsx
  src/components/LoginForms.jsx
  src/components/LoginPage.jsx
  src/context/Provider.jsx
  src/styles/Categories.css
  src/styles/Food.css
  src/styles/FoodPage.css
  src/styles/Header.css
  src/styles/inputSearch.css
Labels: Code Review

#14 iniciando criação da pagina de detalhes
  package-lock.json
  package.json
  src/App.js
  src/components/DetailsHeader.jsx
  src/components/DetailsIngredients.jsx
  src/components/DetailsInstructions.jsx
  src/components/DetailsPage.jsx
  src/components/DetailsVideo.jsx
  src/components/Food.jsx
  src/components/FoodList.jsx
  src/components/LoginPage.jsx
  src/context/Provider.jsx
  src/services/findData.js
  src/services/foodAPI.js
  src/styles/DetailsHeader.css
  src/styles/DetailsIngredients.css
  src/styles/DetailsInstructions.css
  src/styles/DetailsVideo.css
  src/styles/Food.css
Labels: Code Review

#13 Tela de Explorar Ingredientes | App Receitas
  src/App.js
  src/components/IngredientsExploreScreen.jsx
  src/components/IngredientsFromAPI.jsx
  src/context/Provider.jsx
  src/styles/ingredientsExploreScreen.css
Labels: Code Review

#19 Tela de explorar origem | coruja
  src/App.js
  src/components/ExploreFood.jsx
  src/components/ExploreOrigin.jsx
  src/components/ExploreOriginDropdown.jsx
  src/components/ExploreOriginProducts.jsx
  src/context/Provider.jsx
  src/services/foodAPI.js
  src/styles/ExploreOrigin.css
  src/styles/ExploreOriginDropdown.css
  src/styles/ExploreOriginProducts.css
Labels: Code Review
